name: Need team's approval
on: pull_request_review
jobs:
  labelsWhenApproved:
    runs-on: ubuntu-latest
    steps:
      - name: Add Label
      - uses: pullreminders/label-when-approved-action@master
        env:
          APPROVALS: "1"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }
          ADD_LABEL: "approved"
      
      
